import 'package:art_seller_demo/src/features/products/domain/offer.dart';
import 'package:art_seller_demo/src/features/products/domain/product.dart';

/// Test products to be used until a data source is implemented

final kTestOffers = [
  Offer(
    id: '1',
    idProduct: '1',
    imageUrl: 'https://cdnstorage.sendbig.com/unreal/female.webp',
    name: 'Mario',
    surname: 'Rossi',
    proposal: 700,
    time: DateTime.now(),
  ),
  Offer(
    id: '2',
    idProduct: '1',
    imageUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
    name: 'Luigi',
    surname: 'Verdi',
    proposal: 600,
    time: DateTime.now(),
  ),
  Offer(
    id: '3',
    idProduct: '1',
    imageUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
    name: 'Giovanna',
    surname: 'Bianchi',
    proposal: 800,
    time: DateTime.now(),
  ),
  Offer(
    id: '4',
    idProduct: '2',
    imageUrl: 'https://randomuser.me/api/portraits/women/72.jpg',
    name: 'Paola',
    surname: 'Neri',
    proposal: 750,
    time: DateTime.now(),
  ),
  Offer(
    id: '5',
    idProduct: '2',
    imageUrl: 'https://randomuser.me/api/portraits/men/57.jpg',
    name: 'Marco',
    surname: 'Gialli',
    proposal: 900,
    time: DateTime.now(),
  ),
  Offer(
    id: '6',
    idProduct: '3',
    imageUrl: 'https://randomuser.me/api/portraits/women/53.jpg',
    name: 'Anna',
    surname: 'Rosa',
    proposal: 680,
    time: DateTime.now(),
  ),
  Offer(
    id: '7',
    idProduct: '3',
    imageUrl: 'https://randomuser.me/api/portraits/men/62.jpg',
    name: 'Carlo',
    surname: 'Marrone',
    proposal: 720,
    time: DateTime.now(),
  ),
  Offer(
    id: '8',
    idProduct: '1',
    imageUrl: 'https://randomuser.me/api/portraits/women/48.jpg',
    name: 'Elena',
    surname: 'Blu',
    proposal: 820,
    time: DateTime.now(),
  ),
  Offer(
    id: '9',
    idProduct: '2',
    imageUrl: 'https://randomuser.me/api/portraits/men/94.jpg',
    name: 'Roberto',
    surname: 'Arancio',
    proposal: 680,
    time: DateTime.now(),
  ),
  Offer(
    id: '10',
    idProduct: '4',
    imageUrl: 'https://randomuser.me/api/portraits/women/62.jpg',
    name: 'Laura',
    surname: 'Viola',
    proposal: 950,
    time: DateTime.now(),
  ),
];
